//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainStormer_Project.BrainStormRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassQuestions", Namespace="http://schemas.datacontract.org/2004/07/BrainStomerService")]
    [System.SerializableAttribute()]
    public partial class ClassQuestions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Option1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Option2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Option3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Option1 {
            get {
                return this.Option1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Option1Field, value) != true)) {
                    this.Option1Field = value;
                    this.RaisePropertyChanged("Option1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Option2 {
            get {
                return this.Option2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Option2Field, value) != true)) {
                    this.Option2Field = value;
                    this.RaisePropertyChanged("Option2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Option3 {
            get {
                return this.Option3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Option3Field, value) != true)) {
                    this.Option3Field = value;
                    this.RaisePropertyChanged("Option3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrainStormRef.IWCFBrainStormer")]
    public interface IWCFBrainStormer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBrainStormer/ListQuestions", ReplyAction="http://tempuri.org/IWCFBrainStormer/ListQuestionsResponse")]
        System.Collections.Generic.List<string> ListQuestions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBrainStormer/ListQuestions", ReplyAction="http://tempuri.org/IWCFBrainStormer/ListQuestionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListQuestionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBrainStormer/getQuestion", ReplyAction="http://tempuri.org/IWCFBrainStormer/getQuestionResponse")]
        BrainStormer_Project.BrainStormRef.ClassQuestions getQuestion(string qid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBrainStormer/getQuestion", ReplyAction="http://tempuri.org/IWCFBrainStormer/getQuestionResponse")]
        System.Threading.Tasks.Task<BrainStormer_Project.BrainStormRef.ClassQuestions> getQuestionAsync(string qid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBrainStormer/getOptions", ReplyAction="http://tempuri.org/IWCFBrainStormer/getOptionsResponse")]
        System.Collections.Generic.List<string> getOptions(string qids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBrainStormer/getOptions", ReplyAction="http://tempuri.org/IWCFBrainStormer/getOptionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> getOptionsAsync(string qids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBrainStormer/loginDb", ReplyAction="http://tempuri.org/IWCFBrainStormer/loginDbResponse")]
        System.Collections.Generic.Dictionary<string, string> loginDb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBrainStormer/loginDb", ReplyAction="http://tempuri.org/IWCFBrainStormer/loginDbResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> loginDbAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFBrainStormerChannel : BrainStormer_Project.BrainStormRef.IWCFBrainStormer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFBrainStormerClient : System.ServiceModel.ClientBase<BrainStormer_Project.BrainStormRef.IWCFBrainStormer>, BrainStormer_Project.BrainStormRef.IWCFBrainStormer {
        
        public WCFBrainStormerClient() {
        }
        
        public WCFBrainStormerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFBrainStormerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFBrainStormerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFBrainStormerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> ListQuestions() {
            return base.Channel.ListQuestions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListQuestionsAsync() {
            return base.Channel.ListQuestionsAsync();
        }
        
        public BrainStormer_Project.BrainStormRef.ClassQuestions getQuestion(string qid) {
            return base.Channel.getQuestion(qid);
        }
        
        public System.Threading.Tasks.Task<BrainStormer_Project.BrainStormRef.ClassQuestions> getQuestionAsync(string qid) {
            return base.Channel.getQuestionAsync(qid);
        }
        
        public System.Collections.Generic.List<string> getOptions(string qids) {
            return base.Channel.getOptions(qids);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> getOptionsAsync(string qids) {
            return base.Channel.getOptionsAsync(qids);
        }
        
        public System.Collections.Generic.Dictionary<string, string> loginDb() {
            return base.Channel.loginDb();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> loginDbAsync() {
            return base.Channel.loginDbAsync();
        }
    }
}
